spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: czxy
    password: l87289610
    url: jdbc:mysql://rm-m5e32862t94h42445qo.mysql.rds.aliyuncs.com:3306/czxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
logstrategy:
  request: true
token:
  expire: 30000
czxy:
  wechat:
    appId: wx657fdaf188aec6b1
    secret: df7522936b9653b37b8feae7a940514d
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${czxy.wechat.appId}&secret=${czxy.wechat.secret}&code=%s&grant_type=authorization_code
aliyun:
  oss:
    endPoint: YjNOekxXTnVMV0psYVdwcGJtY3VZV3hwZVhWdVkzTXVZMjl0
    #    accessKey: VEZSQlNUUkhOVFZ5YjNkdFJtRk9NVGhaVkhGdE5IUlQ=
    accessKey: VEZSQlNUUkhORFF5TVZjM1l6bEROMXBMT0VGUlUzRlg=
    accessKeySecret: UTBkMVN6RTJWV294U0dGeVJrczFjRnBhTWtGdk5Ia3liVVZvVUU5cQ==
    bucket: Y0hKdlpDMWplbmg1