spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/czxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  main:
    allow-bean-definition-overriding: true
logstrategy:
  request: true
token:
  expire: 6000
czxy:
  wechat:
    appId: wx657fdaf188aec6b1
    secret: df7522936b9653b37b8feae7a940514d
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${czxy.wechat.appId}&secret=${czxy.wechat.secret}&code=%s&grant_type=authorization_code
aliyun:
  oss:
    endPoint: YjNOekxXTnVMV05vWlc1blpIVXVZV3hwZVhWdVkzTXVZMjl0
#    accessKey: VEZSQlNUUkhOVFZ5YjNkdFJtRk9NVGhaVkhGdE5IUlQ=
    accessKey: VEZSQlNUUkhORFF5TVZjM1l6bEROMXBMT0VGUlUzRlg=
    accessKeySecret: UTBkMVN6RTJWV294U0dGeVJrczFjRnBhTWtGdk5Ia3liVVZvVUU5cQ==
    bucket: WkdWMkxXTjZlSGs9