spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/czxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  main:
    allow-bean-definition-overriding: true
logstrategy:
  request: true
token:
  expire: 6000
czxy:
  wechat:
    appId: wx786922b9c7cde075
    secret: 1467ab7029c34d735887825039afcef5
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${czxy.wechat.appId}&secret=${czxy.wechat.secret}&code=%s&grant_type=authorization_code
    accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${czxy.wechat.appId}&secret=${czxy.wechat.secret}
    createTag: https://api.weixin.qq.com/cgi-bin/tags/create?access_token=
    addTag: https://api.weixin.qq.com/cgi-bin/tags/members/batchtagging?access_token=
    clearTag: https://api.weixin.qq.com/cgi-bin/tags/members/batchuntagging?access_token=
    sendByTag: https://api.weixin.qq.com/cgi-bin/message/mass/sendall?access_token=
    preview: https://api.weixin.qq.com/cgi-bin/message/mass/preview?access_token=
    uploadnews: https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token=
    msgTag: czxyMsg
    quetionnaire: czxy_paper
  paper: https://djyh5.zyhqh.com/#/questionnaireInfo?id=
  # 文件可预览大小
  max_file: 10240000
aliyun:
  oss:
    endPoint: YjNOekxXTnVMV05vWlc1blpIVXVZV3hwZVhWdVkzTXVZMjl0
#    accessKey: VEZSQlNUUkhOVFZ5YjNkdFJtRk9NVGhaVkhGdE5IUlQ=
    accessKey: VEZSQlNUUkhORFF5TVZjM1l6bEROMXBMT0VGUlUzRlg=
    accessKeySecret: UTBkMVN6RTJWV294U0dGeVJrczFjRnBhTWtGdk5Ia3liVVZvVUU5cQ==
    bucket: WkdWMkxXTjZlSGs9