spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: czxy
    password: l87289610
    url: jdbc:mysql://rm-m5e32862t94h42445125010.mysql.rds.aliyuncs.com:3306/czxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
logstrategy:
  request: true
token:
  expire: 6000