spring:
  servlet:
    multipart:
      #设置单个文件上传大小
      max-file-size: 10MB
      #设置总上传的数据大小
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.98.202.125:3306/czxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
logstrategy:
  request: true
token:
  expire: 6000

czxy:
  wechat:
    appId: wx657fdaf188aec6b1
    secret: df7522936b9653b37b8feae7a940514d
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${czxy.wechat.appId}&secret=${czxy.wechat.secret}&code=%s&grant_type=authorization_code