spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/czxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
logstrategy:
  request: true